name = "cursorhustle"
compatibility_date = "2024-09-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "MY_DB"
database_name = "todo"
database_id = "5a18c6ae-5ba7-4fbb-b7fb-3886c7c6c2b3"
migrations_dir = "./db/migrations"